services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: lemmy_admin
      POSTGRES_PASSWORD: lemmy_password
      POSTGRES_DB: lemmy_airflow_db
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest

  airflow-init:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
      - redis
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
    entrypoint: /bin/bash
    command:
      - -c
      - |
          pip install -r /opt/airflow/requirements.txt
          airflow db init
          airflow users create \
            --username admin \
            --firstname admin \
            --lastname admin \
            --role Admin \
            --email admin@example.com \
            --password admin
    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
      - redis
      - airflow-init
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt &&
               exec airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
      - redis
      - airflow-init
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt &&
               exec airflow scheduler"

  airflow-worker:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
      - redis
      - airflow-init
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt &&
               exec airflow celery worker"

volumes:
  postgres-db-volume: