services:

  # --- Infrastructure ---
  postgres:
    image: postgres:12

  redis:
    image: redis:latest

  # --- Application ---
  airflow-webserver:
    image: apache/airflow:2.7.1

  airflow-scheduler:
    image: apache/airflow:2.7.1

  airflow-worker:
    image: apache/airflow:2.7.1
